# Auto-generated using compose2nix v0.1.8.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };
  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."myproject-service-a" = {
    image = "docker.io/library/nginx:stable-alpine-slim";
    environment = {
      TZ = "America/New_York";
    };
    volumes = [
      "/var/volumes/service-a:/config:rw"
      "storage:/storage:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cpus=0.5"
      "--network-alias=service-a"
      "--network=myproject-default"
    ];
  };
  systemd.services."podman-myproject-service-a" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "no";
      RuntimeMaxSec = lib.mkOverride 500 360;
    };
    unitConfig = {
      Description = lib.mkOverride 500 "This is the service-a container!";
    };
    after = [
      "podman-network-myproject-default.service"
      "podman-volume-storage.service"
    ];
    requires = [
      "podman-network-myproject-default.service"
      "podman-volume-storage.service"
    ];
    partOf = [
      "podman-compose-myproject-root.target"
    ];
    wantedBy = [
      "podman-compose-myproject-root.target"
    ];
    unitConfig.RequiresMountsFor = [
      "/var/volumes/service-a"
    ];
  };
  virtualisation.oci-containers.containers."service-b" = {
    image = "docker.io/library/nginx:stable-alpine-slim";
    environment = {
      TZ = "America/New_York";
    };
    volumes = [
      "/var/volumes/service-b:/config:rw"
      "storage:/storage:rw"
    ];
    dependsOn = [
      "myproject-service-a"
    ];
    log-driver = "journald";
    extraOptions = [
      "--ip=192.168.8.20"
      "--network-alias=service-b"
      "--network=myproject-something"
    ];
  };
  systemd.services."podman-service-b" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "on-failure";
      RuntimeMaxSec = lib.mkOverride 500 360;
    };
    startLimitBurst = 3;
    unitConfig = {
      AllowIsolate = lib.mkOverride 500 false;
      StartLimitIntervalSec = lib.mkOverride 500 "infinity";
    };
    after = [
      "podman-network-myproject-something.service"
      "podman-volume-storage.service"
    ];
    requires = [
      "podman-network-myproject-something.service"
      "podman-volume-storage.service"
    ];
    partOf = [
      "podman-compose-myproject-root.target"
    ];
    unitConfig.UpheldBy = [
      "podman-myproject-service-a.service"
    ];
    wantedBy = [
      "podman-compose-myproject-root.target"
    ];
    unitConfig.RequiresMountsFor = [
      "/var/volumes/service-b"
    ];
  };

  # Networks
  systemd.services."podman-network-myproject-default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.podman}/bin/podman network rm -f myproject-default";
    };
    script = ''
      podman network inspect myproject-default || podman network create myproject-default --opt=isolate=true
    '';
    partOf = [ "podman-compose-myproject-root.target" ];
    wantedBy = [ "podman-compose-myproject-root.target" ];
  };
  systemd.services."podman-network-myproject-something" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.podman}/bin/podman network rm -f myproject-something";
    };
    script = ''
      podman network inspect myproject-something || podman network create myproject-something --opt=isolate=true --subnet=192.168.8.0/24 --gateway=192.168.8.1 --label=test-label=okay
    '';
    partOf = [ "podman-compose-myproject-root.target" ];
    wantedBy = [ "podman-compose-myproject-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-storage" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    unitConfig.RequiresMountsFor = [
      "/mnt/media"
    ];
    script = ''
      podman volume inspect storage || podman volume create storage --opt=device=/mnt/media --opt=o=bind --opt=type=none
    '';
    partOf = [ "podman-compose-myproject-root.target" ];
    wantedBy = [ "podman-compose-myproject-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-myproject-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
