# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."sopstest-app" = {
    image = "docker.io/library/nginx:stable-alpine-slim";
    environmentFiles = [
      config.sops.secrets."env/env-1.env".path
      config.sops.secrets."api.env".path
    ];
    labels = {
      "compose2nix.settings.sops.secrets" = "env/env-1.env,api.env";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=app"
      "--network=sopstest_default"
    ];
  };
  systemd.services."podman-sopstest-app" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-sopstest_default.service"
    ];
    requires = [
      "podman-network-sopstest_default.service"
    ];
    partOf = [
      "podman-compose-sopstest-root.target"
    ];
    wantedBy = [
      "podman-compose-sopstest-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-sopstest_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f sopstest_default";
    };
    script = ''
      podman network inspect sopstest_default || podman network create sopstest_default
    '';
    partOf = [ "podman-compose-sopstest-root.target" ];
    wantedBy = [ "podman-compose-sopstest-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-sopstest-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
