# Reference: https://github.com/skatolo/gh-actions-nixos-tests
name: NixOS

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  nixos-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.21'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: NixOS test
      run: |
        sudo chmod o+rw /dev/kvm
        make nixos-test-verbose
