# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."test-test-group-add-multiple" = {
    image = "alpine:latest";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--group-add=1000"
      "--group-add=audio"
      "--group-add=video"
      "--network-alias=test-group-add-multiple"
      "--network=test_default"
    ];
  };
  systemd.services."docker-test-test-group-add-multiple" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-test_default.service"
    ];
    requires = [
      "docker-network-test_default.service"
    ];
  };
  virtualisation.oci-containers.containers."test-test-group-add-single" = {
    image = "alpine:latest";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--group-add=audio"
      "--network-alias=test-group-add-single"
      "--network=test_default"
    ];
  };
  systemd.services."docker-test-test-group-add-single" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-test_default.service"
    ];
    requires = [
      "docker-network-test_default.service"
    ];
  };

  # Networks
  systemd.services."docker-network-test_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f test_default";
    };
    script = ''
      docker network inspect test_default || docker network create test_default
    '';
    partOf = [ "docker-compose-test-root.target" ];
    wantedBy = [ "docker-compose-test-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-test-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
