# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."test-first" = {
    image = "nginx:latest";
    environment = {
      "CLOUDFLARE_API_KEY" = "yomama";
      "CLOUDFLARE_EMAIL" = "aaa@aaa.com";
      "DEPTH" = "10";
      "DOMAIN" = "hello.us";
      "HOME_DOMAIN" = "hey.hello.us";
      "NAME" = "first";
      "PGID" = "1000";
      "PUID" = "1000";
      "THEMEPARK_THEME" = "potato";
      "TIMEZONE" = "America/New_York";
    };
    environmentFiles = [
      "override.env"
      "testdata/first.env"
      "testdata/input.env"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=first"
      "--network=test_default"
    ];
  };
  systemd.services."podman-test-first" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-test_default.service"
    ];
    requires = [
      "podman-network-test_default.service"
    ];
  };
  virtualisation.oci-containers.containers."test-second" = {
    image = "nginx:latest";
    environment = {
      "DEPTH" = "20";
      "NAME" = "second";
    };
    environmentFiles = [
      "testdata/input.env"
      "testdata/second.env"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=second"
      "--network=test_default"
    ];
  };
  systemd.services."podman-test-second" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-test_default.service"
    ];
    requires = [
      "podman-network-test_default.service"
    ];
  };

  # Networks
  systemd.services."podman-network-test_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f test_default";
    };
    script = ''
      podman network inspect test_default || podman network create test_default
    '';
    partOf = [ "podman-compose-test-root.target" ];
    wantedBy = [ "podman-compose-test-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-test-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
