# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."test-backend" = {
    image = "alpine:latest";
    environmentFiles = [
      config.sops.secrets."folder/example-2.env".path
    ];
    cmd = [ "sleep" "3600" ];
    labels = {
      "compose2nix.settings.sops.secrets" = "folder/example-2.env";
    };
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=backend"
      "--network=test_default"
    ];
  };
  systemd.services."docker-test-backend" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-test_default.service"
    ];
    requires = [
      "docker-network-test_default.service"
    ];
  };
  virtualisation.oci-containers.containers."test-webapp" = {
    image = "nginx:latest";
    environmentFiles = [
      config.sops.secrets."example.env".path
      config.sops.secrets."folder/example-2.env".path
    ];
    ports = [
      "8080:80/tcp"
    ];
    labels = {
      "compose2nix.settings.sops.secrets" = "example.env,folder/example-2.env";
    };
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=webapp"
      "--network=test_default"
    ];
  };
  systemd.services."docker-test-webapp" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-test_default.service"
    ];
    requires = [
      "docker-network-test_default.service"
    ];
  };

  # Networks
  systemd.services."docker-network-test_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f test_default";
    };
    script = ''
      docker network inspect test_default || docker network create test_default
    '';
    partOf = [ "docker-compose-test-root.target" ];
    wantedBy = [ "docker-compose-test-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-test-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
