# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."test-grace" = {
    image = "alpine";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=grace"
      "--network=test_default"
    ];
  };
  systemd.services."docker-test-grace" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
      TimeoutStopSec = lib.mkOverride 90 30;
    };
    unitConfig.Description = "Container test-grace generated by compose2nix.";
    after = [
      "docker-network-test_default.service"
    ];
    requires = [
      "docker-network-test_default.service"
    ];
  };
  virtualisation.oci-containers.containers."test-grace-override" = {
    image = "alpine";
    labels = {
      "compose2nix.systemd.service.TimeoutStopSec" = "60";
    };
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=grace-override"
      "--network=test_default"
    ];
  };
  systemd.services."docker-test-grace-override" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
      TimeoutStopSec = lib.mkOverride 90 60;
    };
    unitConfig.Description = "Container test-grace-override generated by compose2nix.";
    after = [
      "docker-network-test_default.service"
    ];
    requires = [
      "docker-network-test_default.service"
    ];
  };

  # Networks
  systemd.services."docker-network-test_default" = {
    unitConfig.Description = "Network test_default generated by compose2nix.";
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f test_default";
    };
    script = ''
      docker network inspect test_default || docker network create test_default
    '';
    partOf = [ "docker-compose-test-root.target" ];
    wantedBy = [ "docker-compose-test-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-test-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
