# Auto-generated by compose2nix.

{ pkgs, config, ... }:

let
  lib = pkgs.lib;
in

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."test-test-group-add-multiple" = {
    image = "alpine:latest";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--group-add=1000"
      "--group-add=audio"
      "--group-add=video"
      "--network-alias=test-group-add-multiple"
      "--network=test_default"
    ];
  };
  systemd.services."podman-test-test-group-add-multiple" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    unitConfig.Description = "Container test-test-group-add-multiple generated by compose2nix.";
    after = [
      "podman-network-test_default.service"
    ];
    requires = [
      "podman-network-test_default.service"
    ];
  };
  virtualisation.oci-containers.containers."test-test-group-add-single" = {
    image = "alpine:latest";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--group-add=audio"
      "--network-alias=test-group-add-single"
      "--network=test_default"
    ];
  };
  systemd.services."podman-test-test-group-add-single" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    unitConfig.Description = "Container test-test-group-add-single generated by compose2nix.";
    after = [
      "podman-network-test_default.service"
    ];
    requires = [
      "podman-network-test_default.service"
    ];
  };

  # Networks
  systemd.services."podman-network-test_default" = {
    unitConfig.Description = "Network test_default generated by compose2nix.";
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f test_default";
    };
    script = ''
      podman network inspect test_default || podman network create test_default
    '';
    partOf = [ "podman-compose-test-root.target" ];
    wantedBy = [ "podman-compose-test-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-test-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
