# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."test-jellyfin" = {
    image = "lscr.io/linuxserver/jellyfin:latest";
    volumes = [
      "/media/raid/books:/media/books:rw"
      "/media/raid/music:/media/music:rw"
      "test_jellyfin-cache:/cache:rw"
      "test_jellyfin-config:/config:rw"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=jellyfin"
      "--network=test_default"
    ];
  };
  systemd.services."docker-test-jellyfin" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    unitConfig.Description = "Container test-jellyfin generated by compose2nix.";
    after = [
      "docker-network-test_default.service"
      "docker-volume-test_jellyfin-cache.service"
      "docker-volume-test_jellyfin-config.service"
    ];
    requires = [
      "docker-network-test_default.service"
      "docker-volume-test_jellyfin-cache.service"
      "docker-volume-test_jellyfin-config.service"
    ];
  };

  # Networks
  systemd.services."docker-network-test_default" = {
    unitConfig.Description = "Network test_default generated by compose2nix.";
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f test_default";
    };
    script = ''
      docker network inspect test_default || docker network create test_default
    '';
    partOf = [ "docker-compose-test-root.target" ];
    wantedBy = [ "docker-compose-test-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-test_jellyfin-cache" = {
    unitConfig.Description = "Volume test_jellyfin-cache generated by compose2nix.";
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect test_jellyfin-cache || docker volume create test_jellyfin-cache
    '';
    partOf = [ "docker-compose-test-root.target" ];
    wantedBy = [ "docker-compose-test-root.target" ];
  };
  systemd.services."docker-volume-test_jellyfin-config" = {
    unitConfig.Description = "Volume test_jellyfin-config generated by compose2nix.";
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect test_jellyfin-config || docker volume create test_jellyfin-config
    '';
    partOf = [ "docker-compose-test-root.target" ];
    wantedBy = [ "docker-compose-test-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-test-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
