# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."test-test-ulimits-long" = {
    image = "alpine:latest";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=test-ulimits-long"
      "--network=test_default"
      "--ulimit=nofile=1024:2048"
    ];
  };
  systemd.services."docker-test-test-ulimits-long" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-test_default.service"
    ];
    requires = [
      "docker-network-test_default.service"
    ];
  };
  virtualisation.oci-containers.containers."test-test-ulimits-mixed" = {
    image = "alpine:latest";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=test-ulimits-mixed"
      "--network=test_default"
      "--ulimit=memlock=-1"
      "--ulimit=nofile=1024:524288"
      "--ulimit=rtprio=99"
    ];
  };
  systemd.services."docker-test-test-ulimits-mixed" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-test_default.service"
    ];
    requires = [
      "docker-network-test_default.service"
    ];
  };
  virtualisation.oci-containers.containers."test-test-ulimits-short" = {
    image = "alpine:latest";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=test-ulimits-short"
      "--network=test_default"
      "--ulimit=memlock=-1"
      "--ulimit=rtprio=99"
    ];
  };
  systemd.services."docker-test-test-ulimits-short" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-test_default.service"
    ];
    requires = [
      "docker-network-test_default.service"
    ];
  };
  virtualisation.oci-containers.containers."test-test-ulimits-zero" = {
    image = "alpine:latest";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=test-ulimits-zero"
      "--network=test_default"
      "--ulimit=core=0"
      "--ulimit=nofile=0"
    ];
  };
  systemd.services."docker-test-test-ulimits-zero" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-test_default.service"
    ];
    requires = [
      "docker-network-test_default.service"
    ];
  };

  # Networks
  systemd.services."docker-network-test_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f test_default";
    };
    script = ''
      docker network inspect test_default || docker network create test_default
    '';
    partOf = [ "docker-compose-test-root.target" ];
    wantedBy = [ "docker-compose-test-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-test-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
