# Auto-generated by compose2nix.

{ pkgs, ... }:

let
  lib = pkgs.lib;
in

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."test-basic" = {
    image = "alpine:latest";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--init=true"
      "--network-alias=basic"
      "--network=test_default"
    ];
  };
  systemd.services."docker-test-basic" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    unitConfig.Description = "Container test-basic generated by compose2nix.";
    after = [
      "docker-network-test_default.service"
    ];
    requires = [
      "docker-network-test_default.service"
    ];
  };
  virtualisation.oci-containers.containers."test-unset" = {
    image = "alpine:latest";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=unset"
      "--network=test_default"
    ];
  };
  systemd.services."docker-test-unset" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    unitConfig.Description = "Container test-unset generated by compose2nix.";
    after = [
      "docker-network-test_default.service"
    ];
    requires = [
      "docker-network-test_default.service"
    ];
  };

  # Networks
  systemd.services."docker-network-test_default" = {
    unitConfig.Description = "Network test_default generated by compose2nix.";
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f test_default";
    };
    script = ''
      docker network inspect test_default || docker network create test_default
    '';
    partOf = [ "docker-compose-test-root.target" ];
    wantedBy = [ "docker-compose-test-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-test-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
